
import { Category, MaintenanceWorker } from './types';

export const CATEGORIES: Category[] = [
  { id: 'plumbing', name: 'Plomberie', icon: 'Droplets', description: 'Fuites, robinetterie, sanitaires' },
  { id: 'electrical', name: 'Électricité', icon: 'Zap', description: 'Installation, dépannage, mise aux normes' },
  { id: 'woodwork', name: 'Menuiserie', icon: 'Hammer', description: 'Portes, fenêtres, meubles sur mesure' },
  { id: 'it', name: 'Informatique', icon: 'Monitor', description: 'Réparation, installation, dépannage' },
  { id: 'hvac', name: 'Climatisation', icon: 'Snowflake', description: 'Installation, entretien, réparation' },
  { id: 'painting', name: 'Peinture', icon: 'Paintbrush', description: 'Intérieur, extérieur, décoration' },
];

export const MOCK_WORKERS: MaintenanceWorker[] = [
  {
    id: '1',
    name: 'Samuel Ebongue',
    category: 'plumbing',
    rating: 4.8,
    reviews: 127,
    experience: '15 ans',
    hourlyRate: 5000,
    status: 'online',
    location: { lat: 4.0511, lng: 9.7679, address: 'Douala, Akwa' },
    phone: '+237 670 12 34 56',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    skills: ['Plomberie', 'Climatisation'],
  },
  {
    id: '2',
    name: 'Marie Ngo Ngue',
    category: 'electrical',
    rating: 4.9,
    reviews: 89,
    experience: '10 ans',
    hourlyRate: 7500,
    status: 'online',
    location: { lat: 3.8480, lng: 11.5021, address: 'Yaoundé, Bastos' },
    phone: '+237 690 76 54 32',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    skills: ['Électricité'],
  },
  {
    id: '3',
    name: 'Kevin Tagne',
    category: 'it',
    rating: 4.6,
    reviews: 45,
    experience: '8 ans',
    hourlyRate: 10000,
    status: 'online',
    location: { lat: 4.0615, lng: 9.7085, address: 'Douala, Bonanjo' },
    phone: '+237 655 22 33 44',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    skills: ['Informatique'],
  },
  {
    id: '4',
    name: 'Lucas Kamga',
    category: 'painting',
    rating: 4.8,
    reviews: 112,
    experience: '12 ans',
    hourlyRate: 4000,
    status: 'online',
    location: { lat: 3.8667, lng: 11.5167, address: 'Yaoundé, Mvan' },
    phone: '+237 677 55 66 77',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    skills: ['Peinture', 'Menuiserie'],
  },
];
